### ISSUE TITLE
Broken Guard in SecurityProvider?

### ISSUE THREAD

**Issue by sergeypugachov** [silexphp/Silex#1623]
After uprading to silex 2.3 and symfony 4 i have an issue. 

Fatal error: Uncaught Pimple\Exception\UnknownIdentifierException: Identifier "security.user_provider.secured_area" is not defined. in S:\Projects\medium\vendor\pimple\pimple\src\Pimple\Container.php:101 Stack trace: #0 S:\Projects\medium\vendor\silex\silex\src\Silex\Provider\SecurityServiceProvider.php(658): Pimple\Container->offsetGet('security.user_p...') #1 S:\Projects\medium\vendor\pimple\pimple\src\Pimple\Container.php(118): Silex\Provider\SecurityServiceProvider->Silex\Provider\{closure}(Object(Silex\Application)) #2 S:\Projects\medium\vendor\silex\silex\src\Silex\Provider\SecurityServiceProvider.php(336): Pimple\Container->offsetGet('security.authen...') #3 [internal function]: Silex\Provider\SecurityServiceProvider->Silex\Provider\{closure}('security.authen...') #4 S:\Projects\medium\vendor\silex\silex\src\Silex\Provider\SecurityServiceProvider.php(337): array_map(Object(Closure), Array) #5 S:\Projects\medium\vendor\pimple\pimple\src\Pimple\Container.php(118): Silex\Provider\SecurityServiceProvider->Silex\Provide in S:\Projects\medium\vendor\pimple\pimple\src\Pimple\Container.php on line 101

SecurityServiceProvider.php in around of line 658:

        $app['security.authentication_provider.dao._proto'] = $app->protect(function ($name, $options) use ($app) {
            return function () use ($app, $name) {
                return new DaoAuthenticationProvider(
                    $app['security.user_provider.'.$name], //line 658
                    $app['security.user_checker'],
                    $name,
                    $app['security.encoder_factory'],
                    $app['security.hide_user_not_found']
                );
            };
        });

'security.firewalls' configuration (in attachment) doesn't look wrong for me (in attachment). Is it my misconfiguration, or something has been broken?

[composer show.txt](https://github.com/silexphp/Silex/files/1789114/composer.show.txt)
[firewall.txt](https://github.com/silexphp/Silex/files/1789118/firewall.txt)

**Comment by stof** [comment]
I still see an issue in your configuration (not sure whether it is the cause of your issue):

- the first firewall is a catch-all, so next ones will never be reached
- the first firewall is named `unsecured_area`, but it still seems to secure things (not securing things would be by setting `security => false`, not `anonymous => false`)

**Comment by hkdobrev** [comment]
@sergeypugachov  Not 100% sure as you haven't showed how you register your user provider, but it seems you are affected by #1630. Could you please test out #1631 and report back? Thanks!
